### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by danpalmer** [felixge/faster-than-c#2]
You used `eval` to parse incoming network data...

... on your servers...

... which have database access.

**Comment by max-mapper** [comment]
hi dan. if you read the article again you'll see @felixge never actually passes incoming network data into `eval` (or even `new Function`)

**Comment by danpalmer** [comment]
``` javascript
var code = 'return {\n';

columns.forEach(function(column) {
  code += '"' + column.name + '":' + 'parser.readColumnValue(),\n';
});

code += '};\n';

var parseRow = new Function('columns', 'parser', code);
```

The article implies that in this code 'columns' and therefore 'column' is from an untrusted data source such as the network, in particular it implies it is used to parse packet headers.

**Comment by felixge** [comment]
> The article implies that in this code 'columns' and therefore 'column' is from an untrusted data source such as the network, in particular it implies it is used to parse packet headers.

Yup, that's correct. I did mention this during my talk, I yet have to bring the README in sync with the actual presentation (will do this asap now).

Anyway, this is obviously trivial to fix, so I'll close this issue once I updated the readme.

**Comment by felixge** [comment]
Ok, clarified this in 18eaffc07cd8c9d440627a8ca301c5b9abb4ecaf.
