### ISSUE TITLE
Benchmarks code

### ISSUE THREAD

**Issue by Sannis** [felixge/faster-than-c#3]
Hi Felix!

My 2 cents about you talk :)

I think it will be nice to have a link to used benchmark code in the article.
Is it the [select benchmark from node-mysql](https://github.com/felixge/node-mysql/blob/master/benchmark/select-100k-blog-rows.js)?

Which node-mysql version is used for last benchmark results?

P.S. Hope to meet you at NodeConfIt ;)

**Comment by felixge** [comment]
Hi,

the benchmark I used is here: https://github.com/felixge/faster-than-c/tree/master/figures/mysql-libs

The exact versions for each lib, node, v8, etc. can be found in the raw data set:

https://github.com/felixge/faster-than-c/tree/master/figures/mysql-libs/results

HTH / Looking forward to meeting you at NodeConfIT!
--fg

**Comment by Sannis** [comment]
Oh, I've been unobservant :( And what about test table structure? The only info I can found is there ir 100000 rows with total 180822241 byte.

**Comment by felixge** [comment]
> Oh, I've been unobservant :( And what about test table structure? The only info I can found is there ir 100000 rows with total 180822241 byte.

Sorry, I have to admit that I didn't have time to include/automate everything : /.

Anyway, here is the table + data I used: http://felixge.s3.amazonaws.com/12/blog_posts_2012-11-04.sql.tar.gz

**Comment by Sannis** [comment]
Thanks! I'll try to adopt this data for node-mysql-benchmarks.
